//! Crate root for prost-generated sources (`*.rs` + `generated_lib.rs`).
//! This is the only file in this directory not generated by prost.
#![allow(clippy::all)]

pub mod agent;
pub mod api_integrations;
pub mod asr;
pub mod asr_settings;
pub mod channels;
pub mod child_overwrites;
pub mod content_filter_settings;
pub mod csat;
pub mod end_function;
pub mod entities;
pub mod experimental_config;
pub mod flows;
pub mod functions;
pub mod guardrails;
pub mod handoff;
pub mod integrations;
pub mod keyphrase_boosting;
pub mod knowledge_base;
pub mod languages;
pub mod llm_settings;
pub mod pronunciations;
pub mod ragdoll;
pub mod sms;
pub mod snapshot;
pub mod start_function;
pub mod stop_keywords;
pub mod testing;
pub mod transcript_corrections;
pub mod translations;
pub mod variables;
pub mod variant;
pub mod voice;

/// Proto package `agent_v2` referenced from nested types inside `artifact`.
pub mod agent_v2 {
    pub use crate::handoff::SipByeHandoffConfig as ByeHandoff;
    pub use crate::handoff::SipInviteHandoffConfig as InviteHandoff;
    pub use crate::handoff::SipReferHandoffConfig as ReferHandoff;
}

/// Generated as a flat file but uses `integrations::…` paths that resolve at crate root when inlined.
pub mod artifact {
    use crate::integrations;
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/artifact.rs"));
}

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_lib.rs"));

#[cfg(test)]
mod tests {
    use super::*;
    use prost::Message;

    #[test]
    fn agent_v2_aliases_match_handoff_types() {
        let _bye: agent_v2::ByeHandoff = handoff::SipByeHandoffConfig {};
        let _invite: agent_v2::InviteHandoff = handoff::SipInviteHandoffConfig {
            phone_number: String::new(),
            outbound_endpoint: String::new(),
            outbound_encryption: String::new(),
        };
        let _refer: agent_v2::ReferHandoff = handoff::SipReferHandoffConfig {
            phone_number: String::new(),
        };
    }

    #[test]
    fn command_batch_roundtrip_encode_decode() {
        let batch = CommandBatch {
            last_known_sequence: 7,
            commands: vec![Command {
                r#type: "variable_create".to_string(),
                metadata: Some(Metadata {
                    created_at: None,
                    created_by: "tester".to_string(),
                }),
                command_id: "cmd-1".to_string(),
                payload: Some(command::Payload::VariableCreate(
                    variables::VariableCreate {
                        id: "var-1".to_string(),
                        name: "my_var".to_string(),
                        references: None,
                    },
                )),
            }],
        };

        let bytes = batch.encode_to_vec();
        let decoded = CommandBatch::decode(bytes.as_slice()).expect("decode command batch");
        assert_eq!(decoded.last_known_sequence, 7);
        assert_eq!(decoded.commands.len(), 1);
        assert_eq!(decoded.commands[0].r#type, "variable_create");
        assert!(matches!(
            decoded.commands[0].payload,
            Some(command::Payload::VariableCreate(_))
        ));
    }
}
