//! Crate root for prost-generated sources (`*.rs` + `generated_lib.rs`).
//! This is the only file in this directory not generated by prost.
#![allow(clippy::all)]

pub mod agent;
pub mod api_integrations;
pub mod asr;
pub mod asr_settings;
pub mod channels;
pub mod content_filter_settings;
pub mod csat;
pub mod end_function;
pub mod entities;
pub mod experimental_config;
pub mod flows;
pub mod functions;
pub mod guardrails;
pub mod handoff;
pub mod integrations;
pub mod keyphrase_boosting;
pub mod knowledge_base;
pub mod languages;
pub mod llm_settings;
pub mod pronunciations;
pub mod ragdoll;
pub mod sms;
pub mod snapshot;
pub mod start_function;
pub mod stop_keywords;
pub mod transcript_corrections;
pub mod translations;
pub mod variables;
pub mod variant;
pub mod voice;

/// Proto package `agent_v2` referenced from nested types inside `artifact`.
pub mod agent_v2 {
    pub use crate::handoff::SipByeHandoffConfig as ByeHandoff;
    pub use crate::handoff::SipInviteHandoffConfig as InviteHandoff;
    pub use crate::handoff::SipReferHandoffConfig as ReferHandoff;
}

/// Generated as a flat file but uses `integrations::…` paths that resolve at crate root when inlined.
pub mod artifact {
    use crate::integrations;
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/artifact.rs"));
}

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_lib.rs"));
