# Copyright PolyAI Limited
# flake8: noqa
# ruff: noqa
# type: ignore
from __future__ import annotations

class KnowledgeBase:
    def __init__(self) -> None: ...
    @property
    def disabled_topics(self) -> list[str]: ...
    def disable_topics(self, topic_names: list[str]) -> None: ...
    def enable_topics(self, topic_names: list[str]) -> None: ...
    def enable_all_topics(self) -> None: ...
