# Copyright PolyAI Limited
__all__ = ["ConversationLogger"]

class ConversationLogger:
    def __init__(self) -> None: ...
    def info(self, content: str, is_pii: bool = False, **kwargs): ...
    def warning(self, content: str, is_pii: bool = False, **kwargs): ...
    def error(self, content: str, is_pii: bool = False, **kwargs): ...
