# Copyright PolyAI Limited
# flake8: noqa
# ruff: noqa
# type: ignore
from __future__ import annotations

from typing import Any

__all__ = ["Memory"]

class Memory:
    def __init__(self, fields: dict[str, Any]) -> None: ...
    def __getitem__(self, name: str) -> Any: ...
    def get(self, name: str, default: Any = None) -> Any | None: ...
    def __contains__(self, name: str) -> bool: ...
    def __len__(self) -> int: ...
    def fields(self) -> dict: ...
    def __setattr__(self, name: str, value: Any): ...
    def __setitem__(self, name: str, value): ...
