name: compute-untested-slop-risk

on:
  pull_request:
  push:
    branches: [main]

jobs:
  compute-untested-slop-risk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Specify Rust toolchain
      run: rustup toolchain install stable --profile minimal
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    - name: Install LLMV Coverage
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Install cargo-crap
      run: cargo install cargo-crap
    - name: Run llvm-cov
      run: cargo llvm-cov --lcov --output-path lcov.info
    - name: Run cargo-crap
      run: cargo crap --lcov lcov.info --fail-above --threshold 30
